language: android
android:
    components:
        - platform-tools
        - tools
        - build-tools-23.0.0
        - android-22
        - extra-android-m2repository

jdk:
    - oraclejdk7

before_script:
    - ./depending_repos.sh

script: ./gradlew build
