language: android
android:
    components:
        - platform-tools
        - tools
        - build-tools-23.0.1
        - android-23
        - extra-android-m2repository

jdk:
    - oraclejdk7

before_script:
    - ./depending_repos.sh
    - pip install -r ./travis/requirements.txt --user

script: ./gradlew build -s

after_success: ./travis/travis_upload_release_to_github.py
